//
{
    "type":"immersiveengineering:cloche",
    "results":[{"item":"item"}],
    "input":{"item":"item"},
    "soil":[
        {"item":"item"},
        {"item":"item"}
    ],
    "time":value,
    "render":{"type":"generic","block":"blcok"}
}
