//
{
    "type":"immersiveengineering:crusher",
    "secondaries":[],
    "result":{"tag":"tag"},
    "conditions":[{"value":{"tag":"tag","type":"forge:tag_empty"},"type":"forge:not"}],
    "input":{"item":"item"},
    "energy":value
}
